### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by apvlv** [in03/proxima#275]
Hello,

thank you for this project! When I install  and run the CLI with

`pipx install git+https://github.com/in03/proxima`

I get the following error:

`ModuleNotFoundError: No module named 'proxima' `

Maybe I'm doing something wrong? I tried it on two machines with MacOS Ventura.

Thank you!

**Comment by in03** [comment]
Hey @apvlv!

Sorry to hear you're having issues!
I pushed a fix. Tested and working on Ventura for me. 
Let me know if it's working now for you.

Thanks for your interest!
